name: (NodeJS) pipeline base CI

# Policies run job in branches
on:
  workflow_call:
    inputs:
      # Globals
      globals_node_version:
        description: 'Version of nodeJS to use'
        required: true
        type: string
      globals_package_manager:
        description: 'Declare the package manager as used, yarn or npm'
        required: true
        type: string
      globals_runner_name:
        description: 'Declare runner name to steps'
        required: true
        type: string

      # install_deps
      job_install_deps_container_runner_image:
        description: 'Declare container runner image to steps'
        required: true
        type: string
      job_install_deps_install_args:
        description: 'Arguments of install to use'
        required: false
        default: "install"
        type: string

      # build_app
      job_build_app_container_runner_image:
        description: 'Declare container runner image to steps'
        required: true
        type: string
      job_build_app_build_args:
        description: 'Arguments of build to use'
        required: true
        type: string

      # build_image
      job_build_image_container_runner_image:
        description: 'Declare container runner image to steps'
        required: true
        type: string

      # build_helm
      job_build_helm_container_runner_image:
        description: 'Declare container runner image to steps'
        required: true
        type: string

      # upload_artifacts
      job_build_helm_docker_registry_nexus_url:
        description: 'Private Docker registry Url'
        required: true
        type: string
      job_build_helm_nexus_repository_helm_url:
        description: 'Private Helm repository Url'
        required: true
        type: string

jobs:
  # Workflow reference => (NodeJS) Install deps and Lint
  install_deps:
    name: "DevSecOps - Dependencies install"
    uses: ./.github/workflows/install.yml
    with:
      reusable_runner_name: "${{ inputs.globals_runner_name }}"
      reusable_container_runner_image: "${{ inputs.job_install_deps_container_runner_image }}"
      reusable_package_manager: "${{ inputs.globals_package_manager }}"
      reusable_node_version: "${{ inputs.globals_node_version }}"

  # Workflow reference => (NodeJS) Build app
  build_app:
    name: "DevSecOps - Build App"
    uses: ./.github/workflows/build.yml
    with:
      reusable_runner_name: "${{ inputs.globals_runner_name }}"
      reusable_container_runner_image: "${{ inputs.job_build_app_container_runner_image }}"
      reusable_package_manager: "${{ inputs.globals_package_manager }}"
      reusable_node_version: "${{ inputs.globals_node_version }}"
      reusable_build_args: "${{ inputs.job_build_app_build_args }}"
    needs:
      - install_deps

  # Workflow reference => (NodeJS) Build image
  build_image:
    name: "DevSecOps - Build Image"
    uses: ./.github/workflows/build-image.yml
    with:
      reusable_runner_name: "${{ inputs.globals_runner_name }}"
      reusable_container_runner_image: "${{ inputs.job_build_image_container_runner_image }}"
      reusable_package_manager: "${{ inputs.globals_package_manager }}"
    needs:
      - build_app

  # Workflow reference => (NodeJS) Build chart
  build_helm:
    name: "DevSecOps - Build Helm Chart"
    uses: ./.github/workflows/build-chart.yml
    with:
      reusable_runner_name: "${{ inputs.globals_runner_name }}"
      reusable_container_runner_image: "${{ inputs.job_build_helm_container_runner_image }}"
    needs:
      - build_image

  # Workflow reference => (NodeJS) Upload Artifacts
  upload_artifacts:
    name: "DevSecOps - Upload Artifacts"
    uses: ./.github/workflows/uploads.yml
    with:
      reusable_runner_name: "${{ inputs.globals_runner_name }}"
      reusable_container_runner_image: "${{ inputs.job_build_helm_container_runner_image }}"
      reusable_docker_registry_nexus_url: "${{ inputs.job_build_helm_docker_registry_nexus_url }}"
      reusable_nexus_repository_helm_url: "${{ inputs.job_build_helm_nexus_repository_helm_url }}"
    needs:
      - build_image
      - build_helm