name: (NodeJS) Build chart

# Policies run job in branches
on:
  workflow_call:
    inputs:
      reusable_runner_name:
        description: 'Declare runner name to steps'
        required: true
        type: string
      reusable_container_runner_image:
        description: 'Declare container runner image to steps'
        required: true
        type: string

jobs:
  # Clean and checkout repositories. Clean workspace is enabled by default
  reusable_build_chart:
    name: Build chart
    runs-on: ${{ inputs.reusable_runner_name }}
    container:
      image: ${{ inputs.reusable_container_runner_image }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout Helm template repository
        uses: actions/checkout@v4
        with:
          repository: devsecops-lab-ciandt/helm-charts
          path: app-sample

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.16.3

      - name: Helm lint
        run: helm lint ./app-sample

      - name: Package Helm chart
        run: helm package ./app-sample

      - name: List directories
        run: |
          ls -lha