# Name workflow in pipeline
name: (NodeJS) Build image

# Workflow sharing policy
on:
  workflow_call:
    inputs:
      reusable_runner_name:
        description: 'Declare runner name to steps'
        required: true
        type: string
      reusable_package_manager:
        description: 'Declare the package manager as used, yarn or npm'
        required: true
        type: string

jobs:
  # Clean and checkout repositories. Clean workspace is enabled by default
  reusable_build_image:
    name: Build container image
    runs-on: ${{ inputs.reusable_runner_name }}
    container:
      image: quay.io/buildah/stable:latest
      options: --security-opt seccomp=unconfined --cap-add all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache image
        uses: actions/cache@v4
        with:
          path: 'my-image.tar'
          key: ${{ github.repository }}-${{ github.run_id }}-${{ github.sha }}
          restore-keys: |
            ${{ github.repository }}-${{ github.ref }}-${{ github.run_id }}-

      - name: Restore cache build (npm)
        if: ${{ inputs.reusable_package_manager == 'npm' }}
        uses: actions/cache@v4
        with:
          path: '**/build'
          key: ${{ github.run_id }}-build-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ github.ref }}-${{ github.run_id }}-build-npm

      - name: Restore cache build (yarn)
        if: ${{ inputs.reusable_package_manager == 'yarn' }}
        uses: actions/cache@v4
        with:
          path: '**/build'
          key: ${{ github.run_id }}-build-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ github.ref }}-${{ github.run_id }}-build-yarn

      - name: Build image
        run: |
          buildah bud --format docker -t my-image:latest .
  
      - name: Save image
        run: |
          buildah push my-image:latest oci-archive:my-image.tar