name: (NodeJS) Build chart

# Policies run job in branches
on:
  workflow_call:
    inputs:
      reusable_runner_name:
        description: 'Declare runner name to steps'
        required: true
        type: string
      reusable_container_runner_image:
        description: 'Declare container runner image to steps'
        required: true
        type: string

jobs:
  # Clean and checkout repositories. Clean workspace is enabled by default
  reusable_build_chart:
    name: Build chart
    runs-on: ${{ inputs.reusable_runner_name }}
    container:
      image: ${{ inputs.reusable_container_runner_image }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout Helm template repository
        uses: actions/checkout@v4
        with:
          repository: devsecops-lab-ciandt/helm-charts
          path: chart-template

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.16.3

      - name: List artifact
        run: ls -lha  

      - name: Helm lint
        run: helm lint ./chart-template/app-sample

      - name: Package Helm chart
        run: helm package ./chart-template/app-sample

      - name: Upload artifact chart
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.run_id }}-chart-${{ github.sha }}
          path: app-sample-0.1.0.tgz
          retention-days: 1